name: CI/CD

on: 
  push:
    branches: 
      - revert-7-3-integrating-cicd

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tachyonbyte/leaderboard

  